version: '3'

tasks:
  install:
    desc: Install the dependencies
    cmds:
      - poetry install

  serve:
    desc: Start a development server
    aliases: [run]
    env:
      MOCKILS_DATA_PATH: test_data
    cmds:
      - poetry run fastapi dev mockils.py

  serve:container:
    desc: Start the server as container
    cmds:
      - podman run -d --rm -p 8080:8080 ghcr.io/deutsche-nationalbibliothek/mockils:main

  test:
    desc: Run pytest
    cmds:
      - poetry run pytest

  testdata:
    desc: Create some test directory structure
    cmds:
      - |
        target=test_data/warc/12345
        mkdir -p $target
        cd $target
        echo "Hallo" > file.txt
        echo "large data" | gzip > large.txt.gz

  build:
    desc: Build the container image
    cmds:
      - podman build -t mockils .

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix
