version: '3'

tasks:
  install:
    desc: Install the dependencies
    cmds:
      - poetry install

  serve:
    desc: Start a development server
    aliases: [run]
    cmds:
      - poetry run fastapi dev mockils.py

  serve:container:
    desc: Start the server as container
    cmds:
      - podman run --rm -p 8080:8080 localhost/mockils

  testdata:
    desc: Create some test directory structure
    cmds:
      - |
        target=data/warc/12345
        mkdir -p $target
        cd $target
        echo "Hallo" > file.txt
        echo "large data" | gzip > large.txt.gz

  build:
    desc: Build the container image
    cmds:
      - podman build -t mockils .

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix
